general_settings:
  database_url: os.environ/DATABASE_URL
model_list:
- litellm_params:
    api_base: http://host.docker.internal:11434
    model: ollama/mistral:latest
  model_name: ollama/mistral
- litellm_params:
    api_key: os.environ/OPENAI_API_KEY
    model: openai/gpt-3.5-turbo
  model_name: gpt-3.5-turbo
- litellm_params:
    api_key: os.environ/OPENAI_API_KEY
    model: openai/gpt-4
  model_name: gpt-4
- litellm_params:
    api_key: os.environ/OPENAI_API_KEY
    model: openai/gpt-4-turbo-preview
  model_name: gpt-4-turbo
- litellm_params:
    api_key: os.environ/TOGETHERAI_API_KEY
    model: together_ai/codellama/CodeLlama-70b-hf
  model_info:
    input_cost_per_token: 9.0e-07
    max_tokens: 32768
    output_cost_per_token: 9.0e-07
  model_name: together_ai/CodeLlama-70b
- litellm_params:
    api_key: os.environ/TOGETHERAI_API_KEY
    model: together_ai/codellama/CodeLlama-70b-Python-hf
  model_info:
    input_cost_per_token: 9.0e-07
    max_tokens: 32768
    output_cost_per_token: 9.0e-07
  model_name: together_ai/CodeLlama-70b-Python
- litellm_params:
    api_key: os.environ/TOGETHERAI_API_KEY
    model: together_ai/deepseek-ai/deepseek-coder-33b-instruct
  model_info:
    input_cost_per_token: 8.0e-07
    max_tokens: 32768
    output_cost_per_token: 8.0e-07
  model_name: together_ai/deepseek-coder-33b
- litellm_params:
    api_key: os.environ/TOGETHERAI_API_KEY
    model: together_ai/NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO
  model_info:
    input_cost_per_token: 6.0e-07
    max_tokens: 32768
    output_cost_per_token: 6.0e-07
  model_name: together_ai/Nous-Hermes-2-Mixtral-8x7B-DPO
- litellm_params:
    api_key: os.environ/TOGETHERAI_API_KEY
    model: together_ai/Qwen/Qwen1.5-72B-Chat
  model_info:
    input_cost_per_token: 9.0e-07
    max_tokens: 32768
    output_cost_per_token: 9.0e-07
  model_name: together_ai/Qwen1.5-72B
- litellm_params:
    api_key: os.environ/TOGETHERAI_API_KEY
    model: together_ai/teknium/OpenHermes-2p5-Mistral-7B
  model_info:
    input_cost_per_token: 5.0e-07
    max_tokens: 32768
    output_cost_per_token: 5.0e-07
  model_name: together_ai/OpenHermes-2.5-7B
- litellm_params:
    api_key: os.environ/MISTRAL_API_KEY
    model: mistral/mistral-medium
  model_name: mistral/medium
- litellm_params:
    api_key: os.environ/ANYSCALE_API_KEY
    model: anyscale/mistralai/Mixtral-8x7B-Instruct-v0.1
  model_info:
    input_cost_per_token: 5.0e-07
    max_tokens: 32768
    output_cost_per_token: 5.0e-07
  model_name: anyscale/Mixtral-8x7B-Instruct-v0.1
- litellm_params:
    api_key: os.environ/DEEPINFRA_API_KEY
    model: deepinfra/cognitivecomputations/dolphin-2.6-mixtral-8x7b
  model_name: deepinfra/dolphin-2.6-mixtral-8x7b
