name: Deploy on Push
on:
  push:
    branches:
      - main
permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      LITELLM_HOSTNAME: ${{ secrets.LITELLM_HOSTNAME }}
      LITELLM_MASTER_KEY: ${{ secrets.LITELLM_MASTER_KEY }}
      LITELLM_SALT_KEY: ${{ secrets.LITELLM_SALT_KEY }}
      LITELLM_UI_USERNAME: ${{ secrets.LITELLM_UI_USERNAME }}
      LITELLM_UI_PASSWORD: ${{ secrets.LITELLM_UI_PASSWORD }}
      OPENWEBUI_HOSTNAME: ${{ secrets.OPENWEBUI_HOSTNAME }}
      WEBUI_SECRET_KEY: ${{ secrets.WEBUI_SECRET_KEY }}
      COMPOSE_PROFILES: ${{ vars.COMPOSE_PROFILES }}
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
      S3_ID: ${{ secrets.S3_ID }}
      S3_SECRET: ${{ secrets.S3_SECRET }}
      S3_REGION: ${{ secrets.S3_REGION }}
      S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
    steps:
      - uses: actions/checkout@v3
      - name: Docker Compose Deployment
        uses: g1ibby/dcd/dcd-deploy@main
        with:
          compose_files: docker-compose.yaml
          target: ${{ secrets.DEPLOY_TARGET }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote_dir: /opt/homellm
